<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":Topics-Custom_exceptions-Checked_exception_with_constructor:main" external.linked.project.path="$MODULE_DIR$/../../../../../Topics/Custom exceptions/Checked exception with constructor" external.root.project.path="$MODULE_DIR$/../../../../.." external.system.id="GRADLE" external.system.module.group="Battleship" external.system.module.type="sourceSet" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager">
    <output url="file://$MODULE_DIR$/../../../../../Topics/Custom exceptions/Checked exception with constructor/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../../Topics/Custom exceptions/Checked exception with constructor/src">
      <sourceFolder url="file://$MODULE_DIR$/../../../../../Topics/Custom exceptions/Checked exception with constructor/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>